### ISSUE TITLE
Lab 9b : no new Date entity display when working on utterances.

### ISSUE THREAD

**Issue by msftnutta** [MicrosoftLearning/AI-102-AIEngineer#184]
#### Step: 7

Description of issue

![image](https://user-images.githubusercontent.com/98095529/229675742-002bad22-7f36-4935-9777-f4343e079537.png)

Repro steps:

1. after completing all steps required, there is no option in the dropdown list to select **Date** entity, please see screen shot for reference.

Compare to the old lab, it was using regex for Date entity, Should we be using Regex instead of Prebuilt ?

**Comment by GraemeMalcolm** [comment]
Lol oks Ike you've included the "?" In your selection. What happens if you just select the date?

Cheers,
G
_____________________________________
Tiny keyboard, chubby fingers - sorry!
________________________________
From: msftnutta ***@***.***>
Sent: Monday, April 3, 2023 8:01:19 PM
To: MicrosoftLearning/AI-102-AIEngineer ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [MicrosoftLearning/AI-102-AIEngineer] Lab 9b (Issue #184)


Lab/Demo: 9b
Task: Add a prebuilt entity
Step: 7

Description of issue

[image]<https://user-images.githubusercontent.com/98095529/229675742-002bad22-7f36-4935-9777-f4343e079537.png>

Repro steps:

  1.  after completing all steps required, there is no option in the dropdown list to select Date entity, please see screen shot for reference.

**Comment by msftnutta** [comment]
@GraemeMalcolm  still no Date entity displays in the dropdown list.

![image](https://user-images.githubusercontent.com/98095529/229827134-dbb25649-3848-46da-bce0-e7547aa7c99a.png)

**Comment by Mihai-Ac** [comment]
Hi @msftnutta ,
Can you confirm you have created the other two entities as well (Weekday and Location)?
By the time we get to this point in the lab, there should be 3 entities created : Location (Learned) , Weekday(Learned, List) and Date (Prebuilt,DateTime). 
Running through the instructions I got this, which is what is expected to show up when running through the lab:
![image](https://user-images.githubusercontent.com/110993710/231755980-b725b358-8e45-4ba4-8812-637ff3e68197.png)

**Comment by ivorb** [comment]
@msftnutta could you respond to my teammate's question above?

**Comment by msftnutta** [comment]
I've tested it today, it looks working fine. so ill close it.
