### ISSUE TITLE
Lab 11 Using Wav file not in LODS

### ISSUE THREAD

**Issue by AndrewConniff** [MicrosoftLearning/AI-102-AIEngineer#59]
# Module: 05
#### Step: 06

Description of issue
If the user cannot use the microphone there is a wave file to use. The wave file provided is time-in-london.wav the updated instructions did not appear in the lab - also ir referenced a time.wav which was not added into the lab folder, and also the name of the the recognizer is listed as speech_recognizer  but in the code it is 'recognizer'.

I was able to get it to work for the user by fixing the code but the wave file asked questions that the LUIS and code was not set up to handle - in short this was a mess - but may be from it not publishing to LODS and having to work with the old and new together.

cheers
Repro steps:

1.
1.
1.

**Comment by GraemeMalcolm** [comment]
The .wav file is in the right folders in the repo. It was added 6 days ago - if you cloned it previously, you'd need to pull to get the latest files.
I can't repro the issues you describe above with the current files in the repo.

**Comment by GraemeMalcolm** [comment]
Update - it seems this is an issue at the LODS end - the latest markdown files aren't being pulled into the lab environment for some reason. Additionally, the LODS environment  has stopped capturing the microphone for some reason (which is what necessitated the update in the first place) I've reported both issues to LODS, but unfortunately there's nothing we can do from a content perspective - the files in thsi repo are up to date (and tested), but they're not getting pulled into the hosted lab environment.
I'll leave this issue active until we hear back from LODS.

**Comment by ZekeStarr** [comment]
We (LODS) have updated the labs so that they fall in line exactly with what Graeme was expecting students to be seeing. In order to see this update, if your lab is currently running, you will need to refresh your lab window. Otherwise, when you resume any saved labs for AI-102, or launch a new lab, you will see the updated instructions.

We were not able to replicate the .wav files not downloading, but if you continue to see this, please don't hesitate to submit a ticket with our support so that we can evaluate the issue as it is ongoing.

On the microphone issue, we have engaged the 3rd party developers responsible for the gateway that is causing the loss of microphone utility. They are working on the issue, but we do not yet have an estimated time of resolution. Thank you Graeme, for accounting for this in your latest updates.

**Comment by GraemeMalcolm** [comment]
I think the point is that the WAV files ARE downloading, but the instructions pane isn't pulling in the latest instructions markdown file, so students have no idea what to do with them. As I understand it, the instructions pane should automatically pull in the latest markdown from GitHub; so any changes we make are automatically reflected there when a new instance of the lab starts (or the user refreshes the browser). That doesn't seem to be happening.


Cheers,
G
____________________
Graeme Malcolm
@graeme_malcolm
________________________________

**Comment by ZekeStarr** [comment]
Yep! That's what we were seeing too. We've re-worked the instructions so that that match your development setup, and sync with GitHub immediately (there can be up to a few minute delay, as we're relaying on the raw GitHub links). Outside of that, the only lingering issue should be the microphone passthrough, which we're getting traction on and hope to have resolved soon.

**Comment by GraemeMalcolm** [comment]
Closing because the instructions issue is resolved - awaiting fix for mic redirection issue
