### ISSUE TITLE
Giving Error "unrecognized arguments:  "  in setup.cmd of Lab -23

### ISSUE THREAD

**Issue by ShubhankarS95** [MicrosoftLearning/AI-102-AIEngineer#79]
In Lab 23-custom-search-skill, of file setup.cmd,  
    where it creates the azure storage, create blob container, then upload the files , creates azure cognitive services and azure cognitive search services.
 But after running the setup.cmd, when I cross checked it in the portal, I found that it is **failing in creating the blob container, and thus unable to upload the files**.
   I think there is a problem in setting up the azure storage key in the following below line in setup.cmd:-

`set key_string=!key_json:[ { "keyName": "key1", "permissions": "Full", "value": "=!
set AZURE_STORAGE_KEY=!key_string:" } ]=!
call az storage container create --account-name ai102str!unique_id! --name margies --public-access blob --auth-mode key --account-key %AZURE_STORAGE_KEY% --output none
call az storage blob upload-batch -d margies -s data --account-name ai102str!unique_id! --auth-mode key --account-key %AZURE_STORAGE_KEY%  --output none
`
Please refer the screenshot for the above error.
![Capture](https://user-images.githubusercontent.com/61277649/131564991-a44d2035-7dfb-4a7a-921a-2f0f03a3b94b.JPG)

**Comment by GraemeMalcolm** [comment]
@drguthals , can you take a look?

**Comment by GraemeMalcolm** [comment]
One point is that you seem to be in a PowerShell console - the labs should be run in the provided VM in the Bash console

**Comment by GraemeMalcolm** [comment]
The labs are designed to be used either in the free online courses on Microsoft Learn or in the classroom-based course delivered by Microsoft learning partners - both of these include a hosted VM environment for the labs.. There are links at https://microsoftlearning.github.io/AI-102-AIEngineer/.
If you're using your own environment, you could try just switching the console type to a Windows command prompt instead of the PowerShell console and try that; but again, we don't really support your own environment - the labs are designed specifically for the hosted VM

**Comment by ShubhankarS95** [comment]
> The labs are designed to be used either in the free online courses on Microsoft Learn or in the classroom-based course delivered by Microsoft learning partners - both of these include a hosted VM environment for the labs.. There are links at https://microsoftlearning.github.io/AI-102-AIEngineer/.
> If you're using your own environment, you could try just switching the console type to a Windows command prompt instead of the PowerShell console and try that; but again, we don't really support your own environment - the labs are designed specifically for the hosted VM

Yes, Sir I Followed the instructions.
